childPipelines:
  scmUrls:
    - git@github.com:tkyi/quickstart-ruby.git#main:lib/test/src
    - git@github.com:tkyi/quickstart-ruby.git
jobs:
  main:
    image: node:8
    steps:
        - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET
